trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerHubImageName: 'seu-usuario/docker-imagem' # Substitua 'seu-usuario/docker-imagem' pelo nome da sua imagem no Docker Hub

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        containerRegistry: 'docker-hub-connection' # Use o nome da sua conexão de serviço aqui
        command: login

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(dockerHubImageName):$(tag)
        
    - task: Docker@2
      inputs:
        containerRegistry: 'ead'
        repository: 'ead'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'